name: publish-pypi
on:
  push:
    tags: 
      - "v*.*.*"
jobs:
  test-fpml-py:
    uses: ./.github/workflows/test-python.yml

  publish-fpml-py-to-pypi:
    needs: test-fpml-py
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build a binary wheel and a source tarball
        run: poetry --project=./python build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
