name: publish-dockerhub
on:
  push:
    tags: 
      - "v*.*.*"
jobs:
  test-fpml-ts:
    uses: ./.github/workflows/test-ts.yml

  publish-fpml-ts-to-dockerhub:
    needs: test-fpml-ts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm --privileged tonistiigi/binfmt --install all
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - run: >-
          docker buildx build --platform linux/arm64,linux/amd64
          --push
          --tag bedasoftware/fhirpath-extract:latest
          --tag bedasoftware/fhirpath-extract:$VERSION
          .
        working-directory: ts/server
