name: test-python
on: [workflow_call]
jobs:
  test-fpml-py:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.9
          - python-version: "3.10"
          - python-version: "3.11"
          - python-version: "3.12"
          - python-version: "3.13"
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Python ${{ matrix.python-version }} sample
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry --project=./python install
      - name: Run lint
        run: poetry --project=./python run ruff check ./python
      - name: Run typecheck
        run: poetry --project=./python run mypy ./python
      - name: Run tests
        run: poetry --project=./python run pytest --cov
